### ISSUE TITLE
Wikidata Backload: Argentina

### ISSUE THREAD

**Issue by jacksonj04** [everypolitician/democratic-commons-tasks#13]
* [x] Senate
* [x] Chamber of Deputies

**Comment by tmtmtmtm** [comment]
Note that because the National Congress doesn't have parliamentary terms, only individual mandates, we'll also need to make sure that prior members who weren't re-elected have an end-date added to their memberships, else they'll still appear to be current.

**Comment by jacksonj04** [comment]
* I've reconciled the winners of the [Senate](https://docs.google.com/spreadsheets/d/1lJbKoqKWOhu7yueuJff1h19v7fIasCKUAOjDk4jmNyo/edit#gid=514555971) and [Chamber of Deputies](https://docs.google.com/spreadsheets/d/1lJbKoqKWOhu7yueuJff1h19v7fIasCKUAOjDk4jmNyo/edit#gid=147070354) with Wikidata
  * New objects have been created for some people and parties where I couldn't immediately find a match after a minute or two of searching, on the basis that future merges are relatively easy to perform if anyone does spot a duplicate.
* As per the [Wikidata Summary Page](https://www.wikidata.org/wiki/Wikidata:WikiProject_every_politician/Argentina), the identifiers for the legislatures are:
  * [`Q2118303`](https://www.wikidata.org/wiki/Q2118303) for the Senate
  * [`Q629133`](https://www.wikidata.org/wiki/Q629133) for the Chamber of Deputies
* The membership identifiers (for `P39`) are:
  * [`Q18711738`](https://www.wikidata.org/wiki/Q18711738) for the Senate
  * [`Q18229570`](https://www.wikidata.org/wiki/Q18229570) for the Chamber of Deputies
* The election itself (for `P2715`) is [`Q24894725`](https://www.wikidata.org/wiki/Q24894725)
* These statements should _not_ have a parliamentary term (`P2937`)
* These statements should have a start time (`P580`) of `2017-12-20`

So, for each person in each legislature, there will be a statement to run through _PositionStatements_ stating:

* Their reconciled object identifier
* The fact it's a `P39`
* ... About their membership of a legislature (`Q18711738` or `Q18229570`)
* ... With a start time (`P580`) of `2017-12-20`
* ... An elected in (`P2715`) of `Q24894725`
* ... An electoral district (`P768`) of the person's reconciled area
* ... A parliamentary group (`P4100`) of the person's reconciled party
* ... A reference URL (`P854`, but represented in QuickStatements as `S854`) for the source URL ([Senators](http://www.senado.gov.ar/senadores/listados/listaSenadoRes) and [Deputies](http://www.diputados.gov.ar/diputados/listadip.html))

And there will be an additional statement generated to run through _QuickStatements_ stating:

* Their reconciled object identifier
* A Facebook profile ID (`P2013`) of the page given in the spreadsheet

The following questions remain:

* Should we also set parliamentary term (`P2937`) explicitly to `none`, since we know this is a thing which the memberships do not have and it isn't simply missing?

**Comment by jacksonj04** [comment]
In addition, the following cleanup tasks should be run:

* [x] All `P39` statements for members whose seats were up for re-election (I can't find a definitive list for this, but we should logically be able to at least come close via a Wikidata query) should have an end time (`P582`) set.
  * I believe this should happen for both members who were re-elected, and those who weren't. A member who wasn't re-elected is no longer in office (hence this `P582` marks the end of their position), a member who was will have a new `P39` for the current mandate, and this `P582` would mark the end of their previous one.
  * [Some relevant conversation in Slack](https://mysociety.slack.com/archives/C0260Q6QL/p1514979369000235)

**Comment by jacksonj04** [comment]
I believe these statements should be those in https://gist.github.com/jacksonj04/469d9db28ccb04ef134405cdcf0ae09e

**Comment by tmtmtmtm** [comment]
> members whose seats were up for re-election (I can't find a definitive list for this)

https://en.wikipedia.org/wiki/List_of_Argentine_senators,_2015%E2%80%932017 and https://en.wikipedia.org/wiki/List_of_Argentine_deputies,_2015%E2%80%932017 show the people whose mandates were ending.

**Comment by jacksonj04** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Reconciliation/position statements for Argentina](https://trello.com/c/5drT9knK/34-reconciliation-position-statements-for-argentina)

**Comment by jacksonj04** [comment]
Senate is now, as far as I can tell, done:

* [Source Data](https://docs.google.com/spreadsheets/d/1lJbKoqKWOhu7yueuJff1h19v7fIasCKUAOjDk4jmNyo/edit#gid=514555971)
* [Wikidata query result](http://tinyurl.com/y6vthlvw) returns 24 matches, which I have double checked correspond as expected
* [Current list of Senators](https://www.wikidata.org/wiki/Wikidata:WikiProject_every_politician/Argentina/data/Senate/current) in Wikidata Project does not show anybody on the list of 2015-17 senators, except those who were re-elected, and where re-elected it shows their current mandate.

nb: The [Prompt](https://www.wikidata.org/wiki/User:Oravrattas/prompts/Argentina/Senate) is still using an outdated scrape of the official site, and as such has a very large set of changes.

**Comment by tmtmtmtm** [comment]
> Wikidata query result returns 24 matches

You'll generally want a P2715 (elected in) on that query too. The data is still good (http://tinyurl.com/yapjs2jw), but noting in case you reuse this one for the lower house.

**Comment by tmtmtmtm** [comment]
> The Prompt is still using an outdated scrape of the official site, and as such has a very large set of changes.

I would suggest adding a new prompt directly against https://morph.io/everypolitician-scrapers/argentina-senate/

**Comment by tmtmtmtm** [comment]
> Current list of Senators in Wikidata Project does not show anybody on the list of 2015-17 senators, except those who were re-elected

I'm getting 73 members in total (http://tinyurl.com/yawyfzvs) rather than 72, so there does seem to be one straggler somewhere.

**Comment by jacksonj04** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Backloading: Argentina Senate](https://trello.com/c/PFw2blzN/64-backloading-argentina-senate)
